languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "6G-Recursive User Plane Architecture"

[params]
  # Short name used in the header, page titles and footer.
  brand = "6G-RUPA"
  description = "6G-RUPA is a recursive, RINA-based user plane architecture for flexible, scalable and energy-efficient 6G mobile networks."
  dateFormat = "2 January 2006"

[params.author]
  name = "Sergio Giménez"
  url = "https://sergiogimenez.com"

[params.contact]
  email = "hi@sergiogimenez.com"
  linkedin = "https://www.linkedin.com/in/sergio-gimenez-anton/"
