# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The menu is ordered by weight from lowest to highest.

[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Research"
pageRef = "research"
weight = 20

[[main]]
name = "Articles"
pageRef = "posts"
weight = 25

[[main]]
name = "News"
pageRef = "news"
weight = 30

[[main]]
name = "Contact"
pageRef = "contact"
weight = 40
